### ISSUE TITLE
Can't Stream Files in railway

### ISSUE THREAD

**Issue by Agent-150** [aceknox/Filestreambot#1]
hey i've deployed this repo in railway, but i can't stream or download anything. bot works perfectly fine even gives links too. but that link is not working.
link: https://0.0.0.0/download/1258

**Comment by aceknox** [comment]
Put your project railway link in env file FQDN= your railway project domain and give port as 80

**Comment by aceknox** [comment]
> 
Put your project railway link in env file FQDN= your railway project domain and give port as 80

**Comment by Agent-150** [comment]
Thnx bro
